### ISSUE TITLE
로딩 관련 오류 수정

### ISSUE THREAD

**Issue by hoyahozz** [YouDongKnowMe/DMU-AOS#89]
## 🤔 목적

> 로딩 중 나타나는 오류 수정

## 📝 TO-DO

- [ ] 로딩 중 화면에 표현되지 말아야 할 컴포넌트 지정 및 로직 수정
- [ ] 데이터 연결 실패 후 다시 화면 접근 시 네트워크에 접근하도록 설정
- [ ] 오늘의 식단 화면 로딩 컴포넌트 추가
